repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        # Ensure isort is compatible with Black
        args: ["--profile=black"]

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        # Set the line length to match isort, if different from the default 88
        args: ["--line-length=88"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0  # Use the latest version or the one that suits your project
    hooks:
      - id: flake8
        # Configure additional options as needed, e.g., to exclude files or directories
        args: ["--exclude=.venv,.git,__pycache__,build,dist"]
        additional_dependencies: [flake8-bugbear, flake8-comprehensions]
